<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Cpa.Domain</RootNamespace>
    <AssemblyName>Cpa.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Entities\PatientCompany.cs" />
    <Compile Remove="Enums\Role.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\*.resx">
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>


</Project>
