<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>BigLion.Application.FunctionalTests</RootNamespace>
        <AssemblyName>BigLion.Application.FunctionalTests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="appsettings.json" />
      <Compile Remove="Features\ReferenceGroups\**" />
      <Compile Remove="Features\ReferenceValues\**" />
      <Compile Remove="Features\Addresses\**" />
      <Compile Remove="Features\Systems\**" />
      <Compile Remove="Features\_Shared\TestDataFactory.cs" />
      <Compile Remove="Features\Patients\Queries\GetPatientByHospitalNumberTests.cs" />
      <Compile Remove="Features\Patients\Queries\GetPatientTests.cs" />
      <Compile Remove="Features\Patients\Queries\GetPatientListTests.cs" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
      <PackageReference Include="Microsoft.Data.SqlClient" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" />
      <PackageReference Include="nunit" />
      <PackageReference Include="NUnit.Analyzers">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="NUnit3TestAdapter" />
      <PackageReference Include="coverlet.collector">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="FluentAssertions" />
      <PackageReference Include="Moq" />
      <PackageReference Include="Respawn" />
      <PackageReference Include="System.Configuration.ConfigurationManager" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\src\API\API.csproj" />
      <ProjectReference Include="..\..\src\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

</Project>
