<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7ce67b68-0428-4039-94fa-0b835f70d161</UserSecretsId>
    <AssemblyName>Cpa.Presentation.API</AssemblyName>
    <RootNamespace>Cpa.Presentation.API</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NSwag.AspNetCore" />
    <PackageReference Include="NSwag.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controllers\AddressesController.cs" />
    <Compile Remove="Controllers\AudiogramsController.cs" />
    <Compile Remove="Controllers\BodyCompositionsController.cs" />
    <Compile Remove="Controllers\CareprovidersController.cs" />
    <Compile Remove="Controllers\CheckupClassesController.cs" />
    <Compile Remove="Controllers\CheckupGroupController.cs" />
    <Compile Remove="Controllers\CheckupItemController.cs" />
    <Compile Remove="Controllers\CheckupTypesController.cs" />
    <Compile Remove="Controllers\CheckupsController.cs" />
    <Compile Remove="Controllers\CustomCommandController.cs" />
    <Compile Remove="Controllers\DentalsController.cs" />
    <Compile Remove="Controllers\HearingController.cs" />
    <Compile Remove="Controllers\HearingHertzController.cs" />
    <Compile Remove="Controllers\LabsController.cs" />
    <Compile Remove="Controllers\LungsController.cs" />
    <Compile Remove="Controllers\OptionsController.cs" />
    <Compile Remove="Controllers\PatientsController.cs" />
    <Compile Remove="Controllers\PhysicalExaminationsController.cs" />
    <Compile Remove="Controllers\RecommendationTemplatesController.cs" />
    <Compile Remove="Controllers\RecommendationsController.cs" />
    <Compile Remove="Controllers\ReferenceGroupController.cs" />
    <Compile Remove="Controllers\ReferenceValueController.cs" />
    <Compile Remove="Controllers\ReportTemplateController.cs" />
    <Compile Remove="Controllers\ReportsController.cs" />
    <Compile Remove="Controllers\SpecialTestController.cs" />
    <Compile Remove="Controllers\VisionsController.cs" />
  </ItemGroup>

</Project>
