/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'buildings-create': RouteRecordInfo<'buildings-create', '/buildings/create', Record<never, never>, Record<never, never>>,
    'buildings-edit-id': RouteRecordInfo<'buildings-edit-id', '/buildings/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'buildings-list': RouteRecordInfo<'buildings-list', '/buildings/list', Record<never, never>, Record<never, never>>,
    'buildings-view-id': RouteRecordInfo<'buildings-view-id', '/buildings/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'contract-bonds-create': RouteRecordInfo<'contract-bonds-create', '/contract-bonds/create', Record<never, never>, Record<never, never>>,
    'contract-bonds-edit-id': RouteRecordInfo<'contract-bonds-edit-id', '/contract-bonds/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'contract-bonds-list': RouteRecordInfo<'contract-bonds-list', '/contract-bonds/list', Record<never, never>, Record<never, never>>,
    'contract-bonds-view-id': RouteRecordInfo<'contract-bonds-view-id', '/contract-bonds/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'contract-committee-types-create': RouteRecordInfo<'contract-committee-types-create', '/contract-committee-types/create', Record<never, never>, Record<never, never>>,
    'contract-committee-types-edit-id': RouteRecordInfo<'contract-committee-types-edit-id', '/contract-committee-types/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'contract-committee-types-list': RouteRecordInfo<'contract-committee-types-list', '/contract-committee-types/list', Record<never, never>, Record<never, never>>,
    'contract-committee-types-view-id': RouteRecordInfo<'contract-committee-types-view-id', '/contract-committee-types/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'contract-products-create': RouteRecordInfo<'contract-products-create', '/contract-products/create', Record<never, never>, Record<never, never>>,
    'contract-products-edit-id': RouteRecordInfo<'contract-products-edit-id', '/contract-products/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'contract-products-list': RouteRecordInfo<'contract-products-list', '/contract-products/list', Record<never, never>, Record<never, never>>,
    'contract-products-view-id': RouteRecordInfo<'contract-products-view-id', '/contract-products/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'contracts-create': RouteRecordInfo<'contracts-create', '/contracts/create', Record<never, never>, Record<never, never>>,
    'contracts-list': RouteRecordInfo<'contracts-list', '/contracts/list', Record<never, never>, Record<never, never>>,
    'contracts-view-id': RouteRecordInfo<'contracts-view-id', '/contracts/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'contract-types-create': RouteRecordInfo<'contract-types-create', '/contract-types/create', Record<never, never>, Record<never, never>>,
    'contract-types-edit-id': RouteRecordInfo<'contract-types-edit-id', '/contract-types/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'contract-types-list': RouteRecordInfo<'contract-types-list', '/contract-types/list', Record<never, never>, Record<never, never>>,
    'contract-types-view-id': RouteRecordInfo<'contract-types-view-id', '/contract-types/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'dashboards': RouteRecordInfo<'dashboards', '/dashboards', Record<never, never>, Record<never, never>>,
    'dashboards-test': RouteRecordInfo<'dashboards-test', '/dashboards/test', Record<never, never>, Record<never, never>>,
    'departments-edit-id': RouteRecordInfo<'departments-edit-id', '/departments/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'departments-list': RouteRecordInfo<'departments-list', '/departments/list', Record<never, never>, Record<never, never>>,
    'departments-view-id': RouteRecordInfo<'departments-view-id', '/departments/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'divisions-create': RouteRecordInfo<'divisions-create', '/divisions/create', Record<never, never>, Record<never, never>>,
    'divisions-edit-id': RouteRecordInfo<'divisions-edit-id', '/divisions/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'divisions-list': RouteRecordInfo<'divisions-list', '/divisions/list', Record<never, never>, Record<never, never>>,
    'divisions-view-id': RouteRecordInfo<'divisions-view-id', '/divisions/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'floors-create': RouteRecordInfo<'floors-create', '/floors/create', Record<never, never>, Record<never, never>>,
    'floors-edit-id': RouteRecordInfo<'floors-edit-id', '/floors/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'floors-list': RouteRecordInfo<'floors-list', '/floors/list', Record<never, never>, Record<never, never>>,
    'floors-view-id': RouteRecordInfo<'floors-view-id', '/floors/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'locations-create': RouteRecordInfo<'locations-create', '/locations/create', Record<never, never>, Record<never, never>>,
    'locations-edit-id': RouteRecordInfo<'locations-edit-id', '/locations/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'locations-list': RouteRecordInfo<'locations-list', '/locations/list', Record<never, never>, Record<never, never>>,
    'locations-view-id': RouteRecordInfo<'locations-view-id', '/locations/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'reference-price-types-create': RouteRecordInfo<'reference-price-types-create', '/reference-price-types/create', Record<never, never>, Record<never, never>>,
    'reference-price-types-edit-id': RouteRecordInfo<'reference-price-types-edit-id', '/reference-price-types/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'reference-price-types-list': RouteRecordInfo<'reference-price-types-list', '/reference-price-types/list', Record<never, never>, Record<never, never>>,
    'reference-price-types-view-id': RouteRecordInfo<'reference-price-types-view-id', '/reference-price-types/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'sectors-create': RouteRecordInfo<'sectors-create', '/sectors/create', Record<never, never>, Record<never, never>>,
    'sectors-edit-id': RouteRecordInfo<'sectors-edit-id', '/sectors/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'sectors-list': RouteRecordInfo<'sectors-list', '/sectors/list', Record<never, never>, Record<never, never>>,
    'sectors-view-id': RouteRecordInfo<'sectors-view-id', '/sectors/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'signin-oidc': RouteRecordInfo<'signin-oidc', '/signin-oidc', Record<never, never>, Record<never, never>>,
    'signout': RouteRecordInfo<'signout', '/signout', Record<never, never>, Record<never, never>>,
    'signout-callback-oidc': RouteRecordInfo<'signout-callback-oidc', '/signout-callback-oidc', Record<never, never>, Record<never, never>>,
    'silent-renew': RouteRecordInfo<'silent-renew', '/silent-renew', Record<never, never>, Record<never, never>>,
    'unit-of-measures-create': RouteRecordInfo<'unit-of-measures-create', '/unit-of-measures/create', Record<never, never>, Record<never, never>>,
    'unit-of-measures-edit-id': RouteRecordInfo<'unit-of-measures-edit-id', '/unit-of-measures/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'unit-of-measures-list': RouteRecordInfo<'unit-of-measures-list', '/unit-of-measures/list', Record<never, never>, Record<never, never>>,
    'unit-of-measures-view-id': RouteRecordInfo<'unit-of-measures-view-id', '/unit-of-measures/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'vendors-create': RouteRecordInfo<'vendors-create', '/vendors/create', Record<never, never>, Record<never, never>>,
    'vendors-edit-id': RouteRecordInfo<'vendors-edit-id', '/vendors/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'vendors-list': RouteRecordInfo<'vendors-list', '/vendors/list', Record<never, never>, Record<never, never>>,
    'vendors-view-id': RouteRecordInfo<'vendors-view-id', '/vendors/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
